#!/bin/bash

#
# Wrote by:   Mr. Outis
#

VERSION="0.2"

function usage() {
  echo \
"""
  NAME:
      catastrophe - Get the cadastre number for a given latitud longitude.

  USAGE:
      catastrophe [options] lat lon

  VERSION:
      $VERSION

  OPTIONS:
      -z                Get zoning data in a csv format.
                        (The CSV headers are:
                          Latitude, Longitude, Cadastre number,
                          Borough, Land use, Levels, Height,
                          Free area percentage, Min living area m2,
                          Density, Max construct area m2, Allowed livings
                        )


      -d                Run cURL with the verbose flag.
      -h                Shows this menu.

  EXAMPLE:
      $ catastrophe 19.401408 -99.201958
      OUTPUT:  037_354_01

  REPOSITORY:
      http://github.com/MrOutis/Catastrophe
"""
  exit 1
}

[ -z "$2" ] && usage


# Flags
FETCH_ZONING_DATA=''
DEBUG_MODE=''

# Parse flags
while getopts 'zdh' flag; do
  case "${flag}" in
    z) FETCH_ZONING_DATA='true' ;;
    d) DEBUG_MODE='true' ;;
    h) usage ;;
  esac
done
shift $(($OPTIND-1))

if [ -z "$DEBUG_MODE" ]
then
  CURL_EXTRA_FLAGS='-s'
else
  CURL_EXTRA_FLAGS='-v'
fi


# WARNING: Dragons ahead!
ROOT_URL="http://ciudadmx.df.gob.mx:8080/seduvi"

LAT=$1
LON=$2

MOUSE_CLICK_X=350
MOUSE_CLICK_Y=400

MAP_WIDTH=700
MAP_HEIGHT=800

# Me want cookie!!!
# Needed for make requests effectively
COOKIE_JAR="./cookies"

function prepare_to_request_account() {
  local ENDPOINT="/busquedageoseduvi/buscarCuentaCatastral"
  local url=$ROOT_URL$ENDPOINT

  # Parameters
  url+="?"

  url+="&xScreen=$MOUSE_CLICK_X"
  url+="&yScreen=$MOUSE_CLICK_Y"
  url+="&x=$LON"
  url+="&y=$LAT"
  url+="&z=0"
  url+="&mapWidth=$MAP_WIDTH"
  url+="&mapHeight=$MAP_HEIGHT"
  url+="&ocultar=1"

  curl $CURL_EXTRA_FLAGS \
       --cookie-jar $COOKIE_JAR \
       -X GET \
       $url |
       grep -o "Ninguna cuenta catastral encontrada"
}

function get_account() {
  local ENDPOINT="/principalMapFrameActualizar.jsp"
  local url=$ROOT_URL$ENDPOINT

  # Parameters
  url+="?"

  url+="&op=-1"
  url+="&x=$LON"
  url+="&y=$LAT"
  url+="&z=1"
  url+="&mapWidth=$MAP_WIDTH"
  url+="&mapHeight=$MAP_HEIGHT"
  url+="&dir=0"
  url+="&xMouseDown=$MOUSE_CLICK_X"
  url+="&yMouseDown=$MOUSE_CLICK_Y"
  url+="&xMouseUp=$MOUSE_CLICK_X"
  url+="&yMouseUp=$MOUSE_CLICK_Y"
  url+="&stepZoom=2"
  url+="&verEscala=1"
  url+="&verVistaAerea=1"
  url+="&verControles=1"
  url+="&xVistaAerea=0"
  url+="&yVistaAerea=0"
  url+="&zVistaAerea=0"
  url+="&setStar=0"
  url+="&sizeVistaAerea=150"
  url+="&topStarGuardado=0"
  url+="&leftStarGuardado=0"
  url+="&displayLayerGuardado=none"
  url+="&topLayerGuardado=0"
  url+="&leftLayerGuardado=0"
  url+="&widthLayerGuardado=0"
  url+="&heightLayerGuardado=0"
  url+="&mapImage=MapStreamServlet\?x=$LON"
  url+="&y=$LAT"
  url+="&z=1.0"
  url+="&mapWidth=$MAP_WIDTH"
  url+="&mapHeight=$MAP_HEIGHT"
  url+="&geosetRutaArchivoPrincipal=D:\\seduvidatos\\cartografia\\Default3.mdf"
  url+="&geosetRutaCarpetaPrincipal=D:\\seduvidatos\\cartografia"
  url+="&recupSession=1"
  url+="&guardarMapa=0"
  url+="&setCopyright=0"
  url+="&xUtm=0"
  url+="&yUtm=0"
  url+="&zFrameVistaAerea=3.0"
  url+="&zMapFrameVistaAerea=1.0"

  local regx_cadastre_number="[[:digit:]]{3}_[[:digit:]]{3}_[[:digit:]]+"
  local regx_borough="c[A-Z][a-zA-Z]*"

  if [ -z "$FETCH_ZONING_DATA" ]
  then
    local search=$regx_cadastre_number
  else
    local search="$regx_borough|$regx_cadastre_number"
  fi

  curl $CURL_EXTRA_FLAGS \
       --cookie $COOKIE_JAR \
       -X GET \
       $url |
       grep -o -E $search
}

function fetch_zoning_data() {
  BOROUGH=$1
  CADASTRE_NUMBER=$2

  local ENDPOINT="/fichasReporte/fichaInformacion.jsp?"
  local url=$ROOT_URL$ENDPOINT

  # Parameters
  url+="?"

  url+="&nombreConexion=$BOROUGH"
  url+="&cuentaCatastral=$CADASTRE_NUMBER"

  local regx_zoning_html="<td class='zon'[^<>]+>[^<>]+<[^<>]+>"
  local regx_remove_html_tags='s/<[^<>]*>//g'

  # Print out the cadastre data with the curled zoning data
  echo "$cadastre_number"
  echo "$borough"

  curl $CURL_EXTRA_FLAGS \
       --cookie $COOKIE_JAR \
       -X GET \
       $url |
       grep -o -E "$regx_zoning_html" |
       sed -e "$regx_remove_html_tags" |
       head -n 8
}

function normalize_zoning_data() {
  sed -r 's/[A-Z]+/\L&/g' |       # All lowercase
  sed -e 's/\.//g' |              # Remove dots
  sed -e 's/,/;/g' |              # Change commas for semicolons
  sed -e 's/-\*-/NA/g'            # Put not available data
}

function data_to_csv() {
  echo $LAT,$LON,$(paste -s -d ',')
}

prepare_to_request_account

if [ -z "$FETCH_ZONING_DATA" ]
then
  get_account
else
  read -d "\n" borough cadastre_number <<<$(get_account)

  fetch_zoning_data $borough $cadastre_number |
  normalize_zoning_data |
  data_to_csv
fi
